### ISSUE TITLE
testtttt

### ISSUE THREAD

**Issue by RicardoBachmann** [RicardoBachmann/visible-borders-detroit2#2]
## Fetch APi chuchch 

**As a** user,
**I want to** see a detailed list of all Project Green Light (PGL) Partners in Detroit,
**so that** i can get an overview about the dimension of camera surveillance in public space.

## Description

<img width="661" alt="user_story_01" src="https://user-images.githubusercontent.com/55979464/175764531-1a5c5f77-6666-47b9-8458-2ed8cd6256fb.png" width=320px>

## Acceptance criteria: 

- [x] Each PGL-Partner is rendered in card with details from API 
- [x] List of partners is vertical scrollable  
- [x] Error message appears if API is not available

## Complexity

Small to Medium

## Tasks

- [x] Create branch `fetch-and-render-api`
- [x] Create  ParticipantCard component
- [x] Render API data in an list
- [x] #3
- [x] Write specs for ParticipantCard component
- [x] Setup Storybook for ParticipantCard
- [x] Display error message if API crash 
- [x] Add base styles
